{% set name = "gradle" %}
{% set version = "6.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/gradle/gradle/archive/v{{ version }}.tar.gz
  sha256: 7ce4b92d6a940e82bdd256a7dc6a259d1edb47f7f7b191a6a2d11aeaf169c8a8

build:
  number: 0
  skip: true  # [win]

requirements:
  host:
    - openjdk >=11

test:
  requires:
    - openjdk >=11
  commands:
    - gradle -v

about:
  home: https://gradle.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Gradle - an open-source build-automation system
  description: |
    Gradle is an open-source build automation tool focused on flexibility and performance. Gradle build scripts are written using a Groovy or Kotlin DSL. Read about Gradle features to learn what is possible with Gradle.
  doc_url: https://docs.gradle.org/current/userguide/userguide.html
  dev_url: https://github.com/gradle/gradle

extra:
  recipe-maintainers:
    - klugem
