{% set version = "9.4.0-M5" %}

package:
  name: gradle
  version: {{ version }}

source:
  url: https://github.com/gradle/gradle/archive/v{{ version }}.tar.gz
  sha256: 25c01bd2d287284207bc5b79fe6fefb115e7fd2d254d2a29d6f70ebe794e5876

build:
  number: 0
  noarch: generic

requirements:
  host:
    # https://github.com/gradle/gradle/blob/v9.0.0/settings.gradle.kts#L334
    - openjdk >=17,<18
  run:
    - __unix  # [unix]
    - __win  # [win]
    - openjdk >=17,<25

test:
  requires:
    - openjdk >=17,<25
  commands:
    - gradle -v
    # gradle doesn't show patch version if it's 0
    - gradle -v | grep -E {{ "\.".join(version.split(".")[:2]) }} || exit 1

about:
  home: https://gradle.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Gradle - an open-source build-automation system
  description: |
    Gradle is an open-source build automation tool focused on flexibility and performance. Gradle build scripts are written using a Groovy or Kotlin DSL. Read about Gradle features to learn what is possible with Gradle.
  doc_url: https://docs.gradle.org/current/userguide/userguide.html
  dev_url: https://github.com/gradle/gradle

extra:
  recipe-maintainers:
    - freundTech
    - klugem
