{% set name = "gradle" %}
{% set version = "7.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/gradle/gradle/archive/v{{ version }}.tar.gz
  sha256: fe2b0e1a163f9347f8837a961e296f826c29face684de12db28a65f793ee8251

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - openjdk >=11

test:
  requires:
    - openjdk >=11
  commands:
    - gradle -v

about:
  home: https://gradle.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Gradle - an open-source build-automation system
  description: |
    Gradle is an open-source build automation tool focused on flexibility and performance. Gradle build scripts are written using a Groovy or Kotlin DSL. Read about Gradle features to learn what is possible with Gradle.
  doc_url: https://docs.gradle.org/current/userguide/userguide.html
  dev_url: https://github.com/gradle/gradle

extra:
  recipe-maintainers:
    - klugem
