{% set version = "9.0.0-M4" %}

package:
  name: gradle
  version: {{ version }}

source:
  url: https://github.com/gradle/gradle/archive/v{{ version }}.tar.gz
  sha256: 13fc092338989cd76487747583301ccaea9ecfaec5f6a219c9ba1b73edab36ab

build:
  number: 0
  noarch: generic

requirements:
  host:
    # See https://github.com/gradle/gradle/blob/v8.9.0/settings.gradle.kts#L321
    - openjdk >=11,<12
  run:
    - __unix  # [unix]
    - __win  # [win]
    - openjdk >=8,<23

test:
  requires:
    - openjdk >=8,<23
  commands:
    - gradle -v
    # gradle doesn't show patch version if it's 0
    - gradle -v | grep -E {{ "\.".join(version.split(".")[:2]) }} || exit 1

about:
  home: https://gradle.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Gradle - an open-source build-automation system
  description: |
    Gradle is an open-source build automation tool focused on flexibility and performance. Gradle build scripts are written using a Groovy or Kotlin DSL. Read about Gradle features to learn what is possible with Gradle.
  doc_url: https://docs.gradle.org/current/userguide/userguide.html
  dev_url: https://github.com/gradle/gradle

extra:
  recipe-maintainers:
    - freundTech
    - klugem
