{% set version = "7.4.2" %}

package:
  name: gradle
  version: {{ version }}

source:
  url: https://github.com/gradle/gradle/archive/v{{ version }}.tar.gz
  sha256: 4cbfde441a8afd96a8503a120402839838e3d6bad95aed5d015e642f9c40668c

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - openjdk >=11,<18

test:
  requires:
    - openjdk >=11,<18
    - m2-grep  # [win]
  commands:
    - gradle -v
    - gradle -v | grep -E "{{ version.replace(".", "\.") }}" || exit 1

about:
  home: https://gradle.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Gradle - an open-source build-automation system
  description: |
    Gradle is an open-source build automation tool focused on flexibility and performance. Gradle build scripts are written using a Groovy or Kotlin DSL. Read about Gradle features to learn what is possible with Gradle.
  doc_url: https://docs.gradle.org/current/userguide/userguide.html
  dev_url: https://github.com/gradle/gradle

extra:
  recipe-maintainers:
    - klugem
